# Generated by Django 3.0.4 on 2020-04-27 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='claims',
        ),
        migrations.AddField(
            model_name='news',
            name='claims',
            field=models.ManyToManyField(to='newsapp.Claim'),
        ),
    ]
