# Generated by Django 3.0.4 on 2020-04-27 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0002_auto_20200427_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('content', models.TextField()),
                ('pub_date', models.DateTimeField()),
                ('last_modification_date', models.DateTimeField(auto_now_add=True)),
                ('short_text', models.CharField(max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('info_type', models.CharField(choices=[('FC', 'Fact checking'), ('FDB', 'Feedback'), ('D', 'Donation'), ('ME', 'Media enquiry'), ('DE', 'Different enquiry')], max_length=100)),
                ('url', models.URLField(blank=True)),
            ],
        ),
    ]
