# Generated by Django 3.0.3 on 2020-04-28 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0003_report_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='last_modification_date',
        ),
        migrations.RemoveField(
            model_name='report',
            name='last_modification_date',
        ),
        migrations.AlterField(
            model_name='news',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
