# Generated by Django 3.0.3 on 2020-04-28 12:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0005_request_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='request',
            name='url',
            field=models.TextField(blank=True),
        ),
    ]
